enum Country {
  empty(isoCode: "", phoneCode: "", name: "", iso3Code: ""),
  af(isoCode: "AF", phoneCode: "93", name: "Afghanistan", iso3Code: "AFG"),
  al(isoCode: "AL", phoneCode: "355", name: "Albania", iso3Code: "ALB"),
  dz(isoCode: "DZ", phoneCode: "213", name: "Algeria", iso3Code: "DZA"),
  as(
      isoCode: "AS",
      phoneCode: "1-684",
      name: "American Samoa",
      iso3Code: "ASM"),
  ad(isoCode: "AD", phoneCode: "376", name: "Andorra", iso3Code: "AND"),
  ao(isoCode: "AO", phoneCode: "244", name: "Angola", iso3Code: "AGO"),
  ai(isoCode: "AI", phoneCode: "1-264", name: "Anguilla", iso3Code: "AIA"),
  aq(isoCode: "AQ", phoneCode: "672", name: "Antarctica", iso3Code: "ATA"),
  ag(
      isoCode: "AG",
      phoneCode: "1-268",
      name: "Antigua and Barbuda",
      iso3Code: "ATG"),
  ar(isoCode: "AR", phoneCode: "54", name: "Argentina", iso3Code: "ARG"),
  am(isoCode: "AM", phoneCode: "374", name: "Armenia", iso3Code: "ARM"),
  aw(isoCode: "AW", phoneCode: "297", name: "Aruba", iso3Code: "ABW"),
  au(isoCode: "AU", phoneCode: "61", name: "Australia", iso3Code: "AUS"),
  at(isoCode: "AT", phoneCode: "43", name: "Austria", iso3Code: "AUT"),
  az(isoCode: "AZ", phoneCode: "994", name: "Azerbaijan", iso3Code: "AZE"),
  bs(isoCode: "BS", phoneCode: "1-242", name: "Bahamas", iso3Code: "BHS"),
  bh(isoCode: "BH", phoneCode: "973", name: "Bahrain", iso3Code: "BHR"),
  bd(isoCode: "BD", phoneCode: "880", name: "Bangladesh", iso3Code: "BGD"),
  bb(isoCode: "BB", phoneCode: "1-246", name: "Barbados", iso3Code: "BRB"),
  by(isoCode: "BY", phoneCode: "375", name: "Belarus", iso3Code: "BLR"),
  be(isoCode: "BE", phoneCode: "32", name: "Belgium", iso3Code: "BEL"),
  bz(isoCode: "BZ", phoneCode: "501", name: "Belize", iso3Code: "BLZ"),
  bj(isoCode: "BJ", phoneCode: "229", name: "Benin", iso3Code: "BEN"),
  bm(isoCode: "BM", phoneCode: "1-441", name: "Bermuda", iso3Code: "BMU"),
  bt(isoCode: "BT", phoneCode: "975", name: "Bhutan", iso3Code: "BTN"),
  bo(
      isoCode: "BO",
      phoneCode: "591",
      name: "Bolivia, Plurinational State of",
      iso3Code: "BOL"),
  ba(
      isoCode: "BA",
      phoneCode: "387",
      name: "Bosnia and Herzegovina",
      iso3Code: "BIH"),
  bw(isoCode: "BW", phoneCode: "267", name: "Botswana", iso3Code: "BWA"),
  bv(isoCode: "BV", phoneCode: "47", name: "Bouvet Island", iso3Code: "BVT"),
  br(isoCode: "BR", phoneCode: "55", name: "Brazil", iso3Code: "BRA"),
  io(
      isoCode: "IO",
      phoneCode: "246",
      name: "British Indian Ocean Territory",
      iso3Code: "IOT"),
  bn(
      isoCode: "BN",
      phoneCode: "673",
      name: "Brunei Darussalam",
      iso3Code: "BRN"),
  bg(isoCode: "BG", phoneCode: "359", name: "Bulgaria", iso3Code: "BGR"),
  bf(isoCode: "BF", phoneCode: "226", name: "Burkina Faso", iso3Code: "BFA"),
  bi(isoCode: "BI", phoneCode: "257", name: "Burundi", iso3Code: "BDI"),
  kh(isoCode: "KH", phoneCode: "855", name: "Cambodia", iso3Code: "KHM"),
  cm(isoCode: "CM", phoneCode: "237", name: "Cameroon", iso3Code: "CMR"),
  ca(isoCode: "CA", phoneCode: "1", name: "Canada", iso3Code: "CAN"),
  cv(isoCode: "CV", phoneCode: "238", name: "Cape Verde", iso3Code: "CPV"),
  bq(
      isoCode: "BQ",
      phoneCode: "599",
      name: "Caribbean Netherlands",
      iso3Code: "BES"),
  ky(
      isoCode: "KY",
      phoneCode: "1-345",
      name: "Cayman Islands",
      iso3Code: "CYM"),
  cf(
      isoCode: "CF",
      phoneCode: "236",
      name: "Central African Republic",
      iso3Code: "CAF"),
  td(isoCode: "TD", phoneCode: "235", name: "Chad", iso3Code: "TCD"),
  cl(isoCode: "CL", phoneCode: "56", name: "Chile", iso3Code: "CHL"),
  cn(isoCode: "CN", phoneCode: "86", name: "China", iso3Code: "CHN"),
  cx(isoCode: "CX", phoneCode: "61", name: "Christmas Island", iso3Code: "CXR"),
  cc(
      isoCode: "CC",
      phoneCode: "61",
      name: "Cocos (Keeling) Islands",
      iso3Code: "CCK"),
  co(isoCode: "CO", phoneCode: "57", name: "Colombia", iso3Code: "COL"),
  km(isoCode: "KM", phoneCode: "269", name: "Comoros", iso3Code: "COM"),
  cg(isoCode: "CG", phoneCode: "242", name: "Congo", iso3Code: "COG"),
  cd(
      isoCode: "CD",
      phoneCode: "243",
      name: "Congo, the Democratic Republic of the",
      iso3Code: "COD"),
  ck(isoCode: "CK", phoneCode: "682", name: "Cook Islands", iso3Code: "COK"),
  cr(isoCode: "CR", phoneCode: "506", name: "Costa Rica", iso3Code: "CRI"),
  hr(isoCode: "HR", phoneCode: "385", name: "Croatia", iso3Code: "HRV"),
  cu(isoCode: "CU", phoneCode: "53", name: "Cuba", iso3Code: "CUB"),
  cw(isoCode: "CW", phoneCode: "599", name: "Curaçao", iso3Code: "CUW"),
  cy(isoCode: "CY", phoneCode: "357", name: "Cyprus", iso3Code: "CYP"),
  cz(isoCode: "CZ", phoneCode: "420", name: "Czech Republic", iso3Code: "CZE"),
  ci(isoCode: "CI", phoneCode: "225", name: "Côte d'Ivoire", iso3Code: "CIV"),
  dk(isoCode: "DK", phoneCode: "45", name: "Denmark", iso3Code: "DNK"),
  dj(isoCode: "DJ", phoneCode: "253", name: "Djibouti", iso3Code: "DJI"),
  dm(isoCode: "DM", phoneCode: "1-767", name: "Dominica", iso3Code: "DMA"),
  dom(
      isoCode: "DO",
      phoneCode: "1-849",
      name: "Dominican Republic",
      iso3Code: "DOM"),
  ec(isoCode: "EC", phoneCode: "593", name: "Ecuador", iso3Code: "ECU"),
  eg(isoCode: "EG", phoneCode: "20", name: "Egypt", iso3Code: "EGY"),
  sv(isoCode: "SV", phoneCode: "503", name: "El Salvador", iso3Code: "SLV"),
  gbEng(isoCode: "GB-ENG", phoneCode: "44", name: "England", iso3Code: "GBR"),
  gq(
      isoCode: "GQ",
      phoneCode: "240",
      name: "Equatorial Guinea",
      iso3Code: "GNQ"),
  er(isoCode: "ER", phoneCode: "291", name: "Eritrea", iso3Code: "ERI"),
  ee(isoCode: "EE", phoneCode: "372", name: "Estonia", iso3Code: "EST"),
  et(isoCode: "ET", phoneCode: "251", name: "Ethiopia", iso3Code: "ETH"),
  fk(
      isoCode: "FK",
      phoneCode: "500",
      name: "Falkland Islands (Malvinas)",
      iso3Code: "FLK"),
  fo(isoCode: "FO", phoneCode: "298", name: "Faroe Islands", iso3Code: "FRO"),
  fj(isoCode: "FJ", phoneCode: "679", name: "Fiji", iso3Code: "FJI"),
  fi(isoCode: "FI", phoneCode: "358", name: "Finland", iso3Code: "FIN"),
  fr(isoCode: "FR", phoneCode: "33", name: "France", iso3Code: "FRA"),
  gf(isoCode: "GF", phoneCode: "594", name: "French Guiana", iso3Code: "GUF"),
  pf(
      isoCode: "PF",
      phoneCode: "689",
      name: "French Polynesia",
      iso3Code: "PYF"),
  tf(
      isoCode: "TF",
      phoneCode: "262",
      name: "French Southern Territories",
      iso3Code: "ATF"),
  ga(isoCode: "GA", phoneCode: "241", name: "Gabon", iso3Code: "GAB"),
  gm(isoCode: "GM", phoneCode: "220", name: "Gambia", iso3Code: "GMB"),
  ge(isoCode: "GE", phoneCode: "995", name: "Georgia", iso3Code: "GEO"),
  de(isoCode: "DE", phoneCode: "49", name: "Germany", iso3Code: "DEU"),
  gh(isoCode: "GH", phoneCode: "233", name: "Ghana", iso3Code: "GHA"),
  gi(isoCode: "GI", phoneCode: "350", name: "Gibraltar", iso3Code: "GIB"),
  gr(isoCode: "GR", phoneCode: "30", name: "Greece", iso3Code: "GRC"),
  gl(isoCode: "GL", phoneCode: "299", name: "Greenland", iso3Code: "GRL"),
  gd(isoCode: "GD", phoneCode: "1-473", name: "Grenada", iso3Code: "GRD"),
  gp(isoCode: "GP", phoneCode: "590", name: "Guadeloupe", iso3Code: "GLP"),
  gu(isoCode: "GU", phoneCode: "1-671", name: "Guam", iso3Code: "GUM"),
  gt(isoCode: "GT", phoneCode: "502", name: "Guatemala", iso3Code: "GTM"),
  gg(isoCode: "GG", phoneCode: "44-1481", name: "Guernsey", iso3Code: "GGY"),
  gn(isoCode: "GN", phoneCode: "224", name: "Guinea", iso3Code: "GIN"),
  gw(isoCode: "GW", phoneCode: "245", name: "Guinea-Bissau", iso3Code: "GNB"),
  gy(isoCode: "GY", phoneCode: "592", name: "Guyana", iso3Code: "GUY"),
  ht(isoCode: "HT", phoneCode: "509", name: "Haiti", iso3Code: "HTI"),
  hm(
      isoCode: "HM",
      phoneCode: "672",
      name: "Heard Island and McDonald Islands",
      iso3Code: "HMD"),
  va(
      isoCode: "VA",
      phoneCode: "379",
      name: "Holy See (Vatican City State)",
      iso3Code: "VAT"),
  hn(isoCode: "HN", phoneCode: "504", name: "Honduras", iso3Code: "HND"),
  hk(isoCode: "HK", phoneCode: "852", name: "Hong Kong", iso3Code: "HKG"),
  hu(isoCode: "HU", phoneCode: "36", name: "Hungary", iso3Code: "HUN"),
  isl(isoCode: "IS", phoneCode: "354", name: "Iceland", iso3Code: "ISL"),
  ind(isoCode: "IN", phoneCode: "91", name: "India", iso3Code: "IND"),
  id(isoCode: "ID", phoneCode: "62", name: "Indonesia", iso3Code: "IDN"),
  ir(
      isoCode: "IR",
      phoneCode: "98",
      name: "Iran, Islamic Republic of",
      iso3Code: "IRN"),
  iq(isoCode: "IQ", phoneCode: "964", name: "Iraq", iso3Code: "IRQ"),
  ie(isoCode: "IE", phoneCode: "353", name: "Ireland", iso3Code: "IRL"),
  im(isoCode: "IM", phoneCode: "44-1624", name: "Isle of Man", iso3Code: "IMN"),
  il(isoCode: "IL", phoneCode: "972", name: "Israel", iso3Code: "ISR"),
  it(isoCode: "IT", phoneCode: "39", name: "Italy", iso3Code: "ITA"),
  jm(isoCode: "JM", phoneCode: "1-876", name: "Jamaica", iso3Code: "JAM"),
  jp(isoCode: "JP", phoneCode: "81", name: "Japan", iso3Code: "JPN"),
  je(isoCode: "JE", phoneCode: "44-1534", name: "Jersey", iso3Code: "JEY"),
  jo(isoCode: "JO", phoneCode: "962", name: "Jordan", iso3Code: "JOR"),
  kz(isoCode: "KZ", phoneCode: "7", name: "Kazakhstan", iso3Code: "KAZ"),
  ke(isoCode: "KE", phoneCode: "254", name: "Kenya", iso3Code: "KEN"),
  ki(isoCode: "KI", phoneCode: "686", name: "Kiribati", iso3Code: "KIR"),
  kp(
      isoCode: "KP",
      phoneCode: "850",
      name: "Korea, Democratic People's Republic of",
      iso3Code: "PRK"),
  kr(
      isoCode: "KR",
      phoneCode: "82",
      name: "Korea, Republic of",
      iso3Code: "KOR"),
  xk(isoCode: "XK", phoneCode: "383", name: "Kosovo", iso3Code: "KOS"),
  kw(isoCode: "KW", phoneCode: "965", name: "Kuwait", iso3Code: "KWT"),
  kg(isoCode: "KG", phoneCode: "996", name: "Kyrgyzstan", iso3Code: "KGZ"),
  la(
      isoCode: "LA",
      phoneCode: "856",
      name: "Lao People's Democratic Republic",
      iso3Code: "LAO"),
  lv(isoCode: "LV", phoneCode: "371", name: "Latvia", iso3Code: "LVA"),
  lb(isoCode: "LB", phoneCode: "961", name: "Lebanon", iso3Code: "LBN"),
  ls(isoCode: "LS", phoneCode: "266", name: "Lesotho", iso3Code: "LSO"),
  lr(isoCode: "LR", phoneCode: "231", name: "Liberia", iso3Code: "LBR"),
  ly(isoCode: "LY", phoneCode: "218", name: "Libya", iso3Code: "LBY"),
  li(isoCode: "LI", phoneCode: "423", name: "Liechtenstein", iso3Code: "LIE"),
  lt(isoCode: "LT", phoneCode: "370", name: "Lithuania", iso3Code: "LTU"),
  lu(isoCode: "LU", phoneCode: "352", name: "Luxembourg", iso3Code: "LUX"),
  mo(isoCode: "MO", phoneCode: "853", name: "Macao", iso3Code: "MAC"),
  mk(
      isoCode: "MK",
      phoneCode: "389",
      name: "Macedonia, the former Yugoslav Republic of",
      iso3Code: "MKD"),
  mg(isoCode: "MG", phoneCode: "261", name: "Madagascar", iso3Code: "MDG"),
  mw(isoCode: "MW", phoneCode: "265", name: "Malawi", iso3Code: "MWI"),
  my(isoCode: "MY", phoneCode: "60", name: "Malaysia", iso3Code: "MYS"),
  mv(isoCode: "MV", phoneCode: "960", name: "Maldives", iso3Code: "MDV"),
  ml(isoCode: "ML", phoneCode: "223", name: "Mali", iso3Code: "MLI"),
  mt(isoCode: "MT", phoneCode: "356", name: "Malta", iso3Code: "MLT"),
  mh(
      isoCode: "MH",
      phoneCode: "692",
      name: "Marshall Islands",
      iso3Code: "MHL"),
  mq(isoCode: "MQ", phoneCode: "596", name: "Martinique", iso3Code: "MTQ"),
  mr(isoCode: "MR", phoneCode: "222", name: "Mauritania", iso3Code: "MRT"),
  mu(isoCode: "MU", phoneCode: "230", name: "Mauritius", iso3Code: "MUS"),
  yt(isoCode: "YT", phoneCode: "262", name: "Mayotte", iso3Code: "MYT"),
  mx(isoCode: "MX", phoneCode: "52", name: "Mexico", iso3Code: "MEX"),
  fm(
      isoCode: "FM",
      phoneCode: "691",
      name: "Micronesia, Federated States of",
      iso3Code: "FSM"),
  md(
      isoCode: "MD",
      phoneCode: "373",
      name: "Moldova, Republic of",
      iso3Code: "MDA"),
  mc(isoCode: "MC", phoneCode: "377", name: "Monaco", iso3Code: "MCO"),
  mn(isoCode: "MN", phoneCode: "976", name: "Mongolia", iso3Code: "MNG"),
  me(isoCode: "ME", phoneCode: "382", name: "Montenegro", iso3Code: "MNE"),
  ms(isoCode: "MS", phoneCode: "1-664", name: "Montserrat", iso3Code: "MSR"),
  ma(isoCode: "MA", phoneCode: "212", name: "Morocco", iso3Code: "MAR"),
  mz(isoCode: "MZ", phoneCode: "258", name: "Mozambique", iso3Code: "MOZ"),
  mm(isoCode: "MM", phoneCode: "95", name: "Myanmar", iso3Code: "MMR"),
  na(isoCode: "NA", phoneCode: "264", name: "Namibia", iso3Code: "NAM"),
  nr(isoCode: "NR", phoneCode: "674", name: "Nauru", iso3Code: "NRU"),
  np(isoCode: "NP", phoneCode: "977", name: "Nepal", iso3Code: "NPL"),
  nl(isoCode: "NL", phoneCode: "31", name: "Netherlands", iso3Code: "NLD"),
  an(
      isoCode: "AN",
      phoneCode: "599",
      name: "Netherlands Antilles",
      iso3Code: "AN"),
  nc(isoCode: "NC", phoneCode: "687", name: "New Caledonia", iso3Code: "NCL"),
  nz(isoCode: "NZ", phoneCode: "64", name: "New Zealand", iso3Code: "NZL"),
  ni(isoCode: "NI", phoneCode: "505", name: "Nicaragua", iso3Code: "NIC"),
  ne(isoCode: "NE", phoneCode: "227", name: "Niger", iso3Code: "NER"),
  ng(isoCode: "NG", phoneCode: "234", name: "Nigeria", iso3Code: "NGA"),
  nu(isoCode: "NU", phoneCode: "683", name: "Niue", iso3Code: "NIU"),
  nf(isoCode: "NF", phoneCode: "672", name: "Norfolk Island", iso3Code: "NFK"),
  gbNir(
      isoCode: "GB-NIR",
      phoneCode: "44",
      name: "Northern Ireland",
      iso3Code: "GBR"),
  mp(
      isoCode: "MP",
      phoneCode: "1-670",
      name: "Northern Mariana Islands",
      iso3Code: "MNP"),
  no(isoCode: "NO", phoneCode: "47", name: "Norway", iso3Code: "NOR"),
  om(isoCode: "OM", phoneCode: "968", name: "Oman", iso3Code: "OMN"),
  pk(isoCode: "PK", phoneCode: "92", name: "Pakistan", iso3Code: "PAK"),
  pw(isoCode: "PW", phoneCode: "680", name: "Palau", iso3Code: "PLW"),
  ps(isoCode: "PS", phoneCode: "970", name: "Palestine", iso3Code: "PSE"),
  pa(isoCode: "PA", phoneCode: "507", name: "Panama", iso3Code: "PAN"),
  pg(
      isoCode: "PG",
      phoneCode: "675",
      name: "Papua New Guinea",
      iso3Code: "PNG"),
  py(isoCode: "PY", phoneCode: "595", name: "Paraguay", iso3Code: "PRY"),
  pe(isoCode: "PE", phoneCode: "51", name: "Peru", iso3Code: "PER"),
  ph(isoCode: "PH", phoneCode: "63", name: "Philippines", iso3Code: "PHL"),
  pn(isoCode: "PN", phoneCode: "64", name: "Pitcairn", iso3Code: "PCN"),
  pl(isoCode: "PL", phoneCode: "48", name: "Poland", iso3Code: "POL"),
  pt(isoCode: "PT", phoneCode: "351", name: "Portugal", iso3Code: "PRT"),
  pr(isoCode: "PR", phoneCode: "1-787", name: "Puerto Rico", iso3Code: "PRI"),
  qa(isoCode: "QA", phoneCode: "974", name: "Qatar", iso3Code: "QAT"),
  ro(isoCode: "RO", phoneCode: "40", name: "Romania", iso3Code: "ROU"),
  ru(
      isoCode: "RU",
      phoneCode: "7",
      name: "Russian Federation",
      iso3Code: "RUS"),
  rw(isoCode: "RW", phoneCode: "250", name: "Rwanda", iso3Code: "RWA"),
  re(isoCode: "RE", phoneCode: "262", name: "Réunion", iso3Code: "REU"),
  bl(
      isoCode: "BL",
      phoneCode: "590",
      name: "Saint Barthélemy",
      iso3Code: "BLM"),
  sh(
      isoCode: "SH",
      phoneCode: "290",
      name: "Saint Helena, Ascension and Tristan da Cunha",
      iso3Code: "SHN"),
  kn(
      isoCode: "KN",
      phoneCode: "1-869",
      name: "Saint Kitts and Nevis",
      iso3Code: "KNA"),
  lc(isoCode: "LC", phoneCode: "1-758", name: "Saint Lucia", iso3Code: "LCA"),
  mf(isoCode: "MF", phoneCode: "590", name: "Saint Martin", iso3Code: "MAF"),
  pm(
      isoCode: "PM",
      phoneCode: "508",
      name: "Saint Pierre and Miquelon",
      iso3Code: "SPM"),
  vc(
      isoCode: "VC",
      phoneCode: "1-784",
      name: "Saint Vincent and the Grenadines",
      iso3Code: "VCT"),
  ws(isoCode: "WS", phoneCode: "685", name: "Samoa", iso3Code: "WSM"),
  sm(isoCode: "SM", phoneCode: "378", name: "San Marino", iso3Code: "SMR"),
  st(
      isoCode: "ST",
      phoneCode: "239",
      name: "Sao Tome and Principe",
      iso3Code: "STP"),
  sa(isoCode: "SA", phoneCode: "966", name: "Saudi Arabia", iso3Code: "SAU"),
  gbSct(isoCode: "GB-SCT", phoneCode: "44", name: "Scotland", iso3Code: "GBR"),
  sn(isoCode: "SN", phoneCode: "221", name: "Senegal", iso3Code: "SEN"),
  rs(isoCode: "RS", phoneCode: "381", name: "Serbia", iso3Code: "SRB"),
  sc(isoCode: "SC", phoneCode: "248", name: "Seychelles", iso3Code: "SYC"),
  sl(isoCode: "SL", phoneCode: "232", name: "Sierra Leone", iso3Code: "SLE"),
  sg(isoCode: "SG", phoneCode: "65", name: "Singapore", iso3Code: "SGP"),
  sx(
      isoCode: "SX",
      phoneCode: "1-721",
      name: "Sint Maarten (Dutch part)",
      iso3Code: "SXM"),
  sk(isoCode: "SK", phoneCode: "421", name: "Slovakia", iso3Code: "SVK"),
  si(isoCode: "SI", phoneCode: "386", name: "Slovenia", iso3Code: "SVN"),
  sb(isoCode: "SB", phoneCode: "677", name: "Solomon Islands", iso3Code: "SLB"),
  so(isoCode: "SO", phoneCode: "252", name: "Somalia", iso3Code: "SOM"),
  za(isoCode: "ZA", phoneCode: "27", name: "South Africa", iso3Code: "ZAF"),
  gs(
      isoCode: "GS",
      phoneCode: "500",
      name: "South Georgia and the South Sandwich Islands",
      iso3Code: "SGS"),
  ss(isoCode: "SS", phoneCode: "211", name: "South Sudan", iso3Code: "SSD"),
  es(isoCode: "ES", phoneCode: "34", name: "Spain", iso3Code: "ESP"),
  lk(isoCode: "LK", phoneCode: "94", name: "Sri Lanka", iso3Code: "LKA"),
  sd(isoCode: "SD", phoneCode: "249", name: "Sudan", iso3Code: "SDN"),
  sr(isoCode: "SR", phoneCode: "597", name: "Suriname", iso3Code: "SUR"),
  sj(
      isoCode: "SJ",
      phoneCode: "47",
      name: "Svalbard and Jan Mayen Islands",
      iso3Code: "SJM"),
  sz(isoCode: "SZ", phoneCode: "268", name: "Swaziland", iso3Code: "SWZ"),
  se(isoCode: "SE", phoneCode: "46", name: "Sweden", iso3Code: "SWE"),
  ch(isoCode: "CH", phoneCode: "41", name: "Switzerland", iso3Code: "CHE"),
  sy(
      isoCode: "SY",
      phoneCode: "963",
      name: "Syrian Arab Republic",
      iso3Code: "SYR"),
  tw(isoCode: "TW", phoneCode: "886", name: "Taiwan", iso3Code: "TWN"),
  tj(isoCode: "TJ", phoneCode: "992", name: "Tajikistan", iso3Code: "TJK"),
  tz(
      isoCode: "TZ",
      phoneCode: "255",
      name: "Tanzania, United Republic of",
      iso3Code: "TZA"),
  th(isoCode: "TH", phoneCode: "66", name: "Thailand", iso3Code: "THA"),
  tl(isoCode: "TL", phoneCode: "670", name: "Timor-Leste", iso3Code: "TLS"),
  tg(isoCode: "TG", phoneCode: "228", name: "Togo", iso3Code: "TGO"),
  tk(isoCode: "TK", phoneCode: "690", name: "Tokelau", iso3Code: "TKL"),
  to(isoCode: "TO", phoneCode: "676", name: "Tonga", iso3Code: "TON"),
  tt(
      isoCode: "TT",
      phoneCode: "1-868",
      name: "Trinidad and Tobago",
      iso3Code: "TTO"),
  tn(isoCode: "TN", phoneCode: "216", name: "Tunisia", iso3Code: "TUN"),
  tr(isoCode: "TR", phoneCode: "90", name: "Turkey", iso3Code: "TUR"),
  tm(isoCode: "TM", phoneCode: "993", name: "Turkmenistan", iso3Code: "TKM"),
  tc(
      isoCode: "TC",
      phoneCode: "1-649",
      name: "Turks and Caicos Islands",
      iso3Code: "TCA"),
  tv(isoCode: "TV", phoneCode: "688", name: "Tuvalu", iso3Code: "TUV"),
  ug(isoCode: "UG", phoneCode: "256", name: "Uganda", iso3Code: "UGA"),
  ua(isoCode: "UA", phoneCode: "380", name: "Ukraine", iso3Code: "UKR"),
  ae(
      isoCode: "AE",
      phoneCode: "971",
      name: "United Arab Emirates",
      iso3Code: "ARE"),
  gb(isoCode: "GB", phoneCode: "44", name: "United Kingdom", iso3Code: "GBR"),
  us(isoCode: "US", phoneCode: "1", name: "United States", iso3Code: "USA"),
  uy(isoCode: "UY", phoneCode: "598", name: "Uruguay", iso3Code: "URY"),
  um(
      isoCode: "UM",
      phoneCode: "1",
      name: "US Minor Outlying Islands",
      iso3Code: "UMI"),
  uz(isoCode: "UZ", phoneCode: "998", name: "Uzbekistan", iso3Code: "UZB"),
  vu(isoCode: "VU", phoneCode: "678", name: "Vanuatu", iso3Code: "VUT"),
  ve(
      isoCode: "VE",
      phoneCode: "58",
      name: "Venezuela, Bolivarian Republic of",
      iso3Code: "VEN"),
  vn(isoCode: "VN", phoneCode: "84", name: "Vietnam", iso3Code: "VNM"),
  vg(
      isoCode: "VG",
      phoneCode: "1-284",
      name: "Virgin Islands, British",
      iso3Code: "VGB"),
  vi(
      isoCode: "VI",
      phoneCode: "1-340",
      name: "Virgin Islands, U.S.",
      iso3Code: "VIR"),
  gbWls(isoCode: "GB-WLS", phoneCode: "44", name: "Wales", iso3Code: "GBR"),
  wf(
      isoCode: "WF",
      phoneCode: "681",
      name: "Wallis and Futuna Islands",
      iso3Code: "WLF"),
  eh(isoCode: "EH", phoneCode: "212", name: "Western Sahara", iso3Code: "ESH"),
  ye(isoCode: "YE", phoneCode: "967", name: "Yemen", iso3Code: "YEM"),
  zm(isoCode: "ZM", phoneCode: "260", name: "Zambia", iso3Code: "ZMB"),
  zw(isoCode: "ZW", phoneCode: "263", name: "Zimbabwe", iso3Code: "ZWE"),
  ax(isoCode: "AX", phoneCode: "358", name: "Åland Islands", iso3Code: "ALA");

  final String name;
  final String isoCode;
  final String iso3Code;
  final String phoneCode;

  const Country(
      {required this.isoCode,
      required this.iso3Code,
      required this.phoneCode,
      required this.name});
}
